shallow_clone: true

configuration:
  - Debug
  - Release

environment:
  matrix:
  - CW_TOOLSET: vs2015
    CW_PLATFORM: win32desktop

install:
  - .\Scripts\genie_win --ci-jobs --vs=%CW_PLATFORM% %CW_TOOLSET%

build:
  parallel: true
  project: .\projects\$(CW_TOOLSET)-$(CW_PLATFORM)\Clockwork.sln
